services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Might not need this port if only accessing through proxy
    environment:
      - DOMAIN=$DOMAIN
      - DB_USERNAME=$(cat db_username.txt)
      - DB_PASSWORD=$(cat db_password.txt)
      - DATABASE_URL=$DATABASE_URL
    depends_on:
      - postgres
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy.VIRTUAL_HOST=$DOMAIN"
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy.PROXY_PASS=http://backend:8080"

  frontend:
    build: ./composeApp
    depends_on:
      - nginx-proxy
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy.VIRTUAL_HOST=$DOMAIN"
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy.PROXY_PASS=http://frontend:80"

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
      - dhparam:/etc/nginx/dhparam
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
      - dhparam:/etc/nginx/dhparam
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy
    environment:
      NGINX_PROXY_CONTAINER: "nginx-proxy"

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_username.txt
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password.txt
      POSTGRES_DB: shrtlin
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_username.txt:/run/secrets/db_username.txt:ro
      - ./db_password.txt:/run/secrets/db_password.txt:ro

volumes:
  certbot-etc:
  certbot-var:
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /tmp/dhparam
      o: bind
  postgres_data: