version: '3.7'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: shrtlin
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
volumes:
  postgres_data: {}