services:
  postgres_test:
    image: postgres:latest
    environment:
      POSTGRES_DB: shrtlin
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis_test:
    image: redislabs/redistimeseries:latest
    container_name: redis_test
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  postgres_data: {}
  redis_data:
