services:
  
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_username
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: shrtlin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - db_username
      - db_password
    networks:
      - app-tier

  backend:
    build:
      context: ../..
      dockerfile: dockers/backend/Dockerfile
    container_name: backend
    restart: always
    depends_on:
      - postgres
    environment:
      - DOMAIN=$DOMAIN
      - VIRTUAL_HOST=$DOMAIN
      - DATABASE_URL=$DATABASE_URL
      - DATABASE_USER_FILE=/run/secrets/db_username
      - DATABASE_PASSWORD_FILE=/run/secrets/db_password
      - LETSENCRYPT_HOST=$DOMAIN
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
      # path to https://shrtl.in/(.+) *with* the suffix path (e.g., https://shrtl.in/abc) to be proxied to the backend
      - VIRTUAL_PATH=~^/(.+)$
    volumes:
      - ../../server/ktor.pk8:/run/secrets/ktor_pk8:ro
      - ../../server/certs/jwks.json:/run/secrets/certs/jwks.json:ro
    secrets:
      - db_username
      - db_password
    networks:
      - app-tier
      - proxy-tier

networks:
  app-tier:
  proxy-tier:
    external: true

volumes:
  postgres_data:

secrets:
  db_username:
    file: ../../db_username.txt
  db_password:
    file: ../../db_password.txt
